language: node_js
os:
  - linux
  - osx
node_js:
  - stable
  - "10.5"
  - "8.11"
  - "6.14"
  - "4.9"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - iojs
  - iojs-v1.0.4
before_install:
  - npm install -g gulp
install:
  - npm install
script:
  - gulp test
after_script:
  - node benchmark 25 100000 50 100

